functionsDirectory = "C:\\Users\\cyrus\\Documents\\lsa-booking\\netlify\\functions"
functionsDirectoryOrigin = "config-v1"
headers = []
redirects = []

[build]
publish = "C:\\Users\\cyrus\\Documents\\lsa-booking\\.next"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"
functions = "C:\\Users\\cyrus\\Documents\\lsa-booking\\netlify\\functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]

[[plugins]]
origin = "config"
package = "@netlify/plugin-nextjs"

[plugins.inputs]