-- Fix: this project's `service_role` never received the standard Supabase default
-- grants on tables in the public schema. Without this, the service-role client
-- (used by the Netlify scheduled slot-generation function, and by admin tooling)
-- cannot read/write any table, even though it should bypass RLS entirely.
grant usage on schema public to service_role;
grant all privileges on all tables in schema public to service_role;
grant all privileges on all sequences in schema public to service_role;
grant all privileges on all functions in schema public to service_role;
alter default privileges in schema public grant all privileges on tables to service_role;
alter default privileges in schema public grant all privileges on sequences to service_role;
alter default privileges in schema public grant all privileges on functions to service_role;

-- ============ DEMO DATA ============
insert into coaches (name, email, phone) values
  ('Marcus Tan', 'marcus.tan@example.com', '+62 812-0000-0001'),
  ('Sarah Widjaja', 'sarah.widjaja@example.com', '+62 812-0000-0002')
on conflict (email) do nothing;

insert into families (primary_parent_name, primary_parent_email, phone) values
  ('The Hartono Family', 'hartono.parent@example.com', '+62 813-0000-0001'),
  ('The Putri Family', 'putri.parent@example.com', '+62 813-0000-0002')
on conflict (primary_parent_email) do nothing;

insert into students (family_id, name, type, grade)
select f.id, 'Adit Hartono', 'hp', '10'
from families f where f.primary_parent_email = 'hartono.parent@example.com'
on conflict do nothing;

insert into students (family_id, name, type, grade)
select f.id, 'Kayla Putri', 'general', '7'
from families f where f.primary_parent_email = 'putri.parent@example.com'
on conflict do nothing;

-- Recurring availability templates (next 8 weeks will be generated by the
-- scheduled function / can be generated immediately via the admin UI).
insert into availability_templates (coach_id, day_of_week, start_time_local, end_time_local, eligibility_type)
select c.id, 2, '15:00', '16:00', 'hp_only'
from coaches c where c.email = 'marcus.tan@example.com'
on conflict do nothing;

insert into availability_templates (coach_id, day_of_week, start_time_local, end_time_local, eligibility_type)
select c.id, 4, '16:00', '17:00', 'open_all'
from coaches c where c.email = 'sarah.widjaja@example.com'
on conflict do nothing;

-- A handful of concrete open slot_instances in the next few days, so the app
-- shows real bookable content immediately (without waiting on the generator job).
insert into slot_instances (coach_id, starts_at, ends_at, eligibility_type, status)
select c.id,
       (date_trunc('day', now()) + interval '1 day' + interval '15 hours')::timestamptz,
       (date_trunc('day', now()) + interval '1 day' + interval '16 hours')::timestamptz,
       'hp_only', 'open'
from coaches c where c.email = 'marcus.tan@example.com'
on conflict (coach_id, starts_at) do nothing;

insert into slot_instances (coach_id, starts_at, ends_at, eligibility_type, status)
select c.id,
       (date_trunc('day', now()) + interval '2 days' + interval '16 hours')::timestamptz,
       (date_trunc('day', now()) + interval '2 days' + interval '17 hours')::timestamptz,
       'open_all', 'open'
from coaches c where c.email = 'sarah.widjaja@example.com'
on conflict (coach_id, starts_at) do nothing;

insert into slot_instances (coach_id, starts_at, ends_at, eligibility_type, status)
select c.id,
       (date_trunc('day', now()) + interval '3 days' + interval '17 hours')::timestamptz,
       (date_trunc('day', now()) + interval '3 days' + interval '18 hours')::timestamptz,
       'general_only', 'open'
from coaches c where c.email = 'marcus.tan@example.com'
on conflict (coach_id, starts_at) do nothing;
